# Generated by Django 6.0.5 on 2026-06-15 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='place',
        ),
    ]
